# Generated by Django 5.1.4 on 2025-06-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lifeobj",
            name="currency",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Currency"
            ),
        ),
        migrations.AlterField(
            model_name="lifeobj",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="Min Price",
            ),
        ),
    ]
