# Generated by Django 5.1.4 on 2025-01-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlightTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "airline",
                    models.CharField(max_length=100, verbose_name="شرکت هواپیمایی"),
                ),
                (
                    "airline_logo",
                    models.ImageField(
                        upload_to="airline_logos/", verbose_name="لوگوی شرکت هواپیمایی"
                    ),
                ),
                (
                    "flight_number",
                    models.CharField(max_length=100, verbose_name="شماره پرواز"),
                ),
                (
                    "travel_type",
                    models.CharField(
                        choices=[
                            ("ECONOMY", "اکونومی"),
                            ("PREMIUM_ECONOMY", "پرمیوم اکونومی"),
                            ("BUSINESS", "بیزینس"),
                            ("PREMIUM_BUSINESS", "پرمیوم بیزینس"),
                            ("FIRST", "فرست"),
                            ("PREMIUM_FIRST", "پرمیوم فرست"),
                        ],
                        max_length=20,
                        verbose_name="نوع سفر",
                    ),
                ),
                ("origin", models.CharField(max_length=100, verbose_name="مبدا")),
                ("destination", models.CharField(max_length=100, verbose_name="مقصد")),
                ("departure_date", models.DateTimeField(verbose_name="تاریخ پرواز")),
                ("arrival_date", models.DateTimeField(verbose_name="تاریخ ورود")),
                (
                    "price_adult",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قیمت بزرگسال"
                    ),
                ),
                (
                    "price_child",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قیمت کودک"
                    ),
                ),
                (
                    "price_infant",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قیمت نوزاد"
                    ),
                ),
            ],
        ),
    ]
