# Generated by Django 5.1.4 on 2025-01-10 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="hotels/", verbose_name="تصویر اصلی"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان هتل")),
                ("location", models.CharField(max_length=200, verbose_name="لوکیشن")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="امتیاز"
                    ),
                ),
                ("amenities", models.TextField(verbose_name="امکانات")),
                ("description", models.TextField(verbose_name="توضیحات")),
            ],
        ),
        migrations.AlterField(
            model_name="flightticket",
            name="airline_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="airline_logos/",
                verbose_name="لوگوی شرکت هواپیمایی",
            ),
        ),
        migrations.CreateModel(
            name="HotelRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_plan",
                    models.CharField(max_length=100, verbose_name="وعده غذایی"),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قیمت هر شب"
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="travel.hotel",
                        verbose_name="هتل",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/", verbose_name="تصویر")),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="travel.hotel",
                        verbose_name="هتل",
                    ),
                ),
            ],
        ),
    ]
