# Generated by Django 5.1.4 on 2025-01-10 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0002_hotel_alter_flightticket_airline_logo_hotelroom_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="tours/images/", verbose_name="تصویر"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("summary", models.TextField(verbose_name="خلاصه")),
                ("description", models.TextField(verbose_name="توضیحات")),
                ("accommodation", models.TextField(verbose_name="اقامت")),
                (
                    "transport_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="حمل و نقل (متن)"
                    ),
                ),
                ("meals", models.TextField(verbose_name="وعده های غذایی")),
                ("start_time", models.DateTimeField(verbose_name="زمان شروع")),
                ("end_time", models.DateTimeField(verbose_name="زمان پایان")),
                (
                    "price_per_person",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="قیمت به ازای هر نفر",
                    ),
                ),
                (
                    "transport_ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="travel.flightticket",
                        verbose_name="حمل و نقل (بلیط پرواز)",
                    ),
                ),
            ],
        ),
    ]
