# Generated by Django 5.1.4 on 2025-01-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0003_tour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="accommodation",
            field=models.CharField(max_length=200, verbose_name="اقامت"),
        ),
        migrations.AlterField(
            model_name="tour",
            name="meals",
            field=models.CharField(max_length=200, verbose_name="وعده های غذایی"),
        ),
        migrations.AlterField(
            model_name="tour",
            name="summary",
            field=models.CharField(max_length=200, verbose_name="خلاصه"),
        ),
        migrations.AlterField(
            model_name="tour",
            name="transport_text",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="حمل و نقل (متن)"
            ),
        ),
    ]
