# Generated by Django 5.1.4 on 2025-01-11 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0004_alter_tour_accommodation_alter_tour_meals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="tour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="travel.tour",
                verbose_name="تور",
            ),
        ),
    ]
