# Generated by Django 5.1.4 on 2025-01-11 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0005_image_tour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotel_images",
                to="travel.hotel",
                verbose_name="هتل",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="tour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tour_images",
                to="travel.tour",
                verbose_name="تور",
            ),
        ),
    ]
