# Generated by Django 5.1.4 on 2025-01-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0006_alter_image_hotel_alter_image_tour"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelroom",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="عنوان"
            ),
        ),
        migrations.AlterField(
            model_name="hotelroom",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
    ]
