# Generated by Django 5.1.4 on 2025-01-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0007_hotelroom_title_alter_hotelroom_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="price_per_person",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="قیمت به ازای هر نفر"
            ),
        ),
    ]
