# Generated by Django 5.1.4 on 2025-01-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0008_alter_tour_price_per_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="rating",
            field=models.DecimalField(
                decimal_places=0, max_digits=3, verbose_name="امتیاز"
            ),
        ),
    ]
