# Generated by Django 5.1.4 on 2025-01-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0009_alter_hotel_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelroom",
            name="price_per_night",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="قیمت هر شب"
            ),
        ),
    ]
