# Generated by Django 5.1.4 on 2025-01-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0010_alter_hotelroom_price_per_night"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="ai_summary",
            field=models.TextField(
                blank=True, null=True, verbose_name="خلاصه هوش مصنوعی"
            ),
        ),
    ]
