# Generated by Django 5.1.4 on 2025-01-17 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0012_tour_image_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=200, verbose_name="روز")),
                ("summary", models.CharField(max_length=200, verbose_name="خلاصه")),
                (
                    "image",
                    models.ImageField(upload_to="tours/images", verbose_name="تصویر"),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_days",
                        to="travel.tour",
                        verbose_name="تور",
                    ),
                ),
            ],
        ),
    ]
