# Generated by Django 5.1.4 on 2025-01-17 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0013_tourday"),
    ]

    operations = [
        migrations.CreateModel(
            name="Providers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(max_length=100, verbose_name="ارائه دهنده"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="قیمت"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=0, max_digits=3, verbose_name="امتیاز"
                    ),
                ),
                ("affiliate_link", models.URLField(verbose_name="لینک")),
                (
                    "flight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_provider",
                        to="travel.flightticket",
                        verbose_name="پرواز",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_provider",
                        to="travel.hotel",
                        verbose_name="هتل",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_provider",
                        to="travel.tour",
                        verbose_name="تور",
                    ),
                ),
            ],
        ),
    ]
