# Generated by Django 5.1.4 on 2025-01-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0014_providers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Providers",
            new_name="Provider",
        ),
    ]
