# Generated by Django 5.1.4 on 2025-01-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0015_rename_providers_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="image_cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="hotels/", verbose_name="تصویر کاور"
            ),
        ),
    ]
