# Generated by Django 5.1.4 on 2025-01-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0016_hotel_image_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="ai_summary",
            field=models.TextField(
                blank=True, null=True, verbose_name="خلاصه هوش مصنوعی"
            ),
        ),
    ]
