# Generated by Django 5.1.4 on 2025-01-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0019_hotel_location_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="active",
            field=models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
        ),
        migrations.AddField(
            model_name="tour",
            name="active",
            field=models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
        ),
    ]
