# Generated by Django 5.1.4 on 2025-01-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0020_hotel_active_tour_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flightticket",
            options={"verbose_name": "پرواز", "verbose_name_plural": "1. پرواز ها"},
        ),
        migrations.AlterModelOptions(
            name="hotel",
            options={"verbose_name": "هتل", "verbose_name_plural": "2. هتل ها"},
        ),
        migrations.AlterModelOptions(
            name="hotelroom",
            options={"verbose_name": "اتاق هتل", "verbose_name_plural": "2.1 اتاق ها"},
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "تصویر", "verbose_name_plural": "4. تصاویر"},
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={"verbose_name": "افیلیت", "verbose_name_plural": "لیست افیلیت"},
        ),
        migrations.AlterModelOptions(
            name="tour",
            options={"verbose_name": "تور", "verbose_name_plural": "3. تور ها"},
        ),
        migrations.AlterModelOptions(
            name="tourday",
            options={
                "verbose_name": "برنامه تور",
                "verbose_name_plural": "3.1 برنامه تور ها",
            },
        ),
        migrations.AddField(
            model_name="flightticket",
            name="active",
            field=models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
        ),
    ]
