# Generated by Django 5.1.4 on 2025-01-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0021_alter_flightticket_options_alter_hotel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="active",
            field=models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
        ),
    ]
