# Generated by Django 5.1.4 on 2025-01-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0022_provider_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourday",
            name="summary",
            field=models.TextField(verbose_name="خلاصه"),
        ),
    ]
