# Generated by Django 5.1.4 on 2025-01-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0023_alter_tourday_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourday",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tours/images",
                verbose_name="تصویر-Optional",
            ),
        ),
    ]
