# Generated by Django 5.1.4 on 2025-02-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0024_alter_tourday_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightticket",
            name="keywords",
            field=models.TextField(blank=True, null=True, verbose_name="کلمات کلیدی"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="keywords",
            field=models.TextField(blank=True, null=True, verbose_name="کلمات کلیدی"),
        ),
        migrations.AddField(
            model_name="provider",
            name="keywords",
            field=models.TextField(blank=True, null=True, verbose_name="کلمات کلیدی"),
        ),
        migrations.AddField(
            model_name="tour",
            name="keywords",
            field=models.TextField(blank=True, null=True, verbose_name="کلمات کلیدی"),
        ),
    ]
