# Generated by Django 5.1.4 on 2025-04-20 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0025_flightticket_keywords_hotel_keywords_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="category")),
                ("description", models.TextField(verbose_name="description")),
                ("image", models.ImageField(upload_to="categories/travel/")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="travel.travelcategory",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Travel Category",
                "verbose_name_plural": "Travel Categories",
            },
        ),
        migrations.AddField(
            model_name="flightticket",
            name="categories",
            field=models.ManyToManyField(
                related_name="flight_categories",
                to="travel.travelcategory",
                verbose_name="categories",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="categories",
            field=models.ManyToManyField(
                related_name="hotel_categories",
                to="travel.travelcategory",
                verbose_name="categories",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="categories",
            field=models.ManyToManyField(
                related_name="tour_categories",
                to="travel.travelcategory",
                verbose_name="categories",
            ),
        ),
    ]
