# Generated by Django 5.1.4 on 2025-04-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0026_travelcategory_flightticket_categories_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="travelcategory",
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
        migrations.AlterField(
            model_name="travelcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/travel/",
                verbose_name="تصویر",
            ),
        ),
    ]
