# Generated by Django 5.1.4 on 2025-04-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0027_alter_travelcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hotelroom",
            options={
                "ordering": ("-price_per_night",),
                "verbose_name": "اتاق هتل",
                "verbose_name_plural": "2.1 اتاق ها",
            },
        ),
        migrations.AlterModelOptions(
            name="travelcategory",
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "5. دسته بندی ها",
            },
        ),
        migrations.AddField(
            model_name="hotelroom",
            name="currency",
            field=models.CharField(max_length=20, null=True, verbose_name="واحد پول"),
        ),
    ]
