# Generated by Django 5.1.4 on 2025-04-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "travel",
            "0028_alter_hotelroom_options_alter_travelcategory_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hotelroom",
            options={
                "ordering": ("price_per_night",),
                "verbose_name": "اتاق هتل",
                "verbose_name_plural": "2.1 اتاق ها",
            },
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="amenities",
        ),
    ]
