# Generated by Django 5.1.4 on 2025-04-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0029_alter_hotelroom_options_remove_hotel_amenities"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="location_url",
            field=models.CharField(
                max_length=200, null=True, verbose_name="آدرس گوگل مپ"
            ),
        ),
    ]
