# Generated by Django 5.1.4 on 2025-04-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0030_hotel_location_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelcategory",
            name="for_flight",
            field=models.BooleanField(default=True, verbose_name="For flight"),
        ),
        migrations.AddField(
            model_name="travelcategory",
            name="for_hotel",
            field=models.BooleanField(default=True, verbose_name="For Hotel"),
        ),
        migrations.AddField(
            model_name="travelcategory",
            name="for_tour",
            field=models.BooleanField(default=True, verbose_name="For tour"),
        ),
    ]
