# Generated by Django 5.1.4 on 2025-04-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0031_travelcategory_for_flight_travelcategory_for_hotel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="currency",
            field=models.CharField(max_length=20, null=True, verbose_name="واحد پول"),
        ),
    ]
