# Generated by Django 5.1.4 on 2025-04-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0033_remove_hotel_ai_summary_remove_tour_accommodation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="meals",
        ),
    ]
