# Generated by Django 5.1.4 on 2025-04-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0034_remove_tour_meals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="image_cover",
        ),
        migrations.AddField(
            model_name="flightticket",
            name="currency",
            field=models.CharField(max_length=20, null=True, verbose_name="واحد پول"),
        ),
    ]
