# Generated by Django 5.1.4 on 2025-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0035_remove_tour_image_cover_flightticket_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("about", models.CharField(max_length=255, verbose_name="About")),
            ],
            options={
                "verbose_name": "ویزا",
                "verbose_name_plural": "6. ویزا",
            },
        ),
    ]
