# Generated by Django 5.1.4 on 2025-04-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0036_visa"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelcategory",
            name="for_visa",
            field=models.BooleanField(default=True, verbose_name="For flight"),
        ),
        migrations.AddField(
            model_name="visa",
            name="categories",
            field=models.ManyToManyField(
                related_name="visa_categories",
                to="travel.travelcategory",
                verbose_name="categories",
            ),
        ),
    ]
