# Generated by Django 5.1.4 on 2025-04-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0037_travelcategory_for_visa_visa_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="visa",
            name="keywords",
            field=models.TextField(null=True, verbose_name="Keywords"),
        ),
        migrations.DeleteModel(
            name="Provider",
        ),
    ]
