# Generated by Django 5.1.4 on 2025-04-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_article_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
