# Generated by Django 5.1.4 on 2025-06-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessObj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="business/images/", verbose_name="Thumbnail"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("summary", models.CharField(max_length=200, verbose_name="Summary")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Min Price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(max_length=20, null=True, verbose_name="Currency"),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
                ),
                (
                    "keywords",
                    models.TextField(blank=True, null=True, verbose_name="کلمات کلیدی"),
                ),
            ],
            options={
                "verbose_name": "1. Business Object",
                "verbose_name_plural": "1. Business Objects",
            },
        ),
    ]
