# Generated by Django 5.1.4 on 2025-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliate_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerlink",
            name="price",
            field=models.BigIntegerField(default=0, verbose_name="Price"),
        ),
    ]
