# Generated by Django 5.1.4 on 2025-04-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliate_module", "0002_providerlink_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerlink",
            name="currency",
            field=models.CharField(default=1, max_length=20, verbose_name="Currency"),
            preserve_default=False,
        ),
    ]
